name: build

on:
  push:
    branches:
      - master
    paths:
      - App/**
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ytnetworks.azurecr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./App
          platforms: linux/amd64
          push: true
          build-args: |
            SEMVER=${{ steps.gitversion.outputs.semVer }}
            ASSEMBLY_SEMVER=${{ steps.gitversion.outputs.assemblySemFileVer }}
          tags: |
            ytnetworks.azurecr.io/recfluence:latest
            ytnetworks.azurecr.io/recfluence:${{ steps.gitversion.outputs.semVer }}
